config/routes.rb
DbAncien::Application.routes.draw do
  resources :experiences

  resources :diplomes

  resources :students

end

app/models/diplome.rb
class Diplome < ActiveRecord::Base
  attr_accessible :name, :student_id
  belongs_to :student
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  attr_accessible :debut, :fin, :poste, :societe, :student_id
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :nom, :photo, :prenom, :promo
  has_many :diplomes
  has_many :experiences
  
  def self.search(params)
    if params[:search]
      Student.find(:all, :conditions => ['nom LIKE ? or prenom LIKE ?', "%#{params[:search]}%" ,"%#{params[:search]}%"])
    else
      Student.order("nom").page(params[:page])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/diplomes_controller.rb
class DiplomesController < ApplicationController
  # GET /diplomes
  # GET /diplomes.json
  def index
    @diplomes = Diplome.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @diplomes }
    end
  end

  # GET /diplomes/1
  # GET /diplomes/1.json
  def show
    @diplome = Diplome.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @diplome }
    end
  end

  # GET /diplomes/new
  # GET /diplomes/new.json
  def new
    @diplome = Diplome.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @diplome }
    end
  end

  # GET /diplomes/1/edit
  def edit
    @diplome = Diplome.find(params[:id])
  end

  # POST /diplomes
  # POST /diplomes.json
  def create
    @diplome = Diplome.new(params[:diplome])

    respond_to do |format|
      if @diplome.save
        format.html { redirect_to @diplome, notice: 'Diplome was successfully created.' }
        format.json { render json: @diplome, status: :created, location: @diplome }
      else
        format.html { render action: "new" }
        format.json { render json: @diplome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /diplomes/1
  # PUT /diplomes/1.json
  def update
    @diplome = Diplome.find(params[:id])

    respond_to do |format|
      if @diplome.update_attributes(params[:diplome])
        format.html { redirect_to @diplome, notice: 'Diplome was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @diplome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diplomes/1
  # DELETE /diplomes/1.json
  def destroy
    @diplome = Diplome.find(params[:id])
    @diplome.destroy

    respond_to do |format|
      format.html { redirect_to diplomes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = Experience.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @experiences }
    end
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @experience = Experience.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @experience }
    end
  end

  # GET /experiences/new
  # GET /experiences/new.json
  def new
    @experience = Experience.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @experience }
    end
  end

  # GET /experiences/1/edit
  def edit
    @experience = Experience.find(params[:id])
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(params[:experience])

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render json: @experience, status: :created, location: @experience }
      else
        format.html { render action: "new" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /experiences/1
  # PUT /experiences/1.json
  def update
    @experience = Experience.find(params[:id])

    respond_to do |format|
      if @experience.update_attributes(params[:experience])
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience = Experience.find(params[:id])
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  def index
    @students = Student.search(params)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    # @student = Student.new
    # 
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { render json: @student }
    # end
  end

  # GET /students/1/edit
  def edit
    # @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    # @student = Student.new(params[:student])
    # 
    #  respond_to do |format|
    #    if @student.save
    #      format.html { redirect_to @student, notice: 'Student was successfully created.' }
    #      format.json { render json: @student, status: :created, location: @student }
    #    else
    #      format.html { render action: "new" }
    #      format.json { render json: @student.errors, status: :unprocessable_entity }
    #    end
    #  end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    # @student = Student.find(params[:id])
    # 
    # respond_to do |format|
    #   if @student.update_attributes(params[:student])
    #     format.html { redirect_to @student, notice: 'Student was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @student.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
   #  @student = Student.find(params[:id])
   #   @student.destroy
   # 
   #   respond_to do |format|
   #     format.html { redirect_to students_url }
   #     format.json { head :no_content }
   #   end
   # 
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diplomes_helper.rb
module DiplomesHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/diplomes/_form.html.erb
<%= form_for(@diplome) do |f| %>
  <% if @diplome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diplome.errors.count, "error") %> prohibited this diplome from being saved:</h2>

      <ul>
      <% @diplome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diplomes/edit.html.erb
<h1>Editing diplome</h1>

<%= render 'form' %>

<%= link_to 'Show', @diplome %> |
<%= link_to 'Back', diplomes_path %>

app/views/diplomes/index.html.erb
<h1>Listing diplomes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Student</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @diplomes.each do |diplome| %>
  <tr>
    <td><%= diplome.name %></td>
    <td><%= diplome.student_id %></td>
    <td><%= link_to 'Show', diplome %></td>
    <td><%= link_to 'Edit', edit_diplome_path(diplome) %></td>
    <td><%= link_to 'Destroy', diplome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Diplome', new_diplome_path %>

app/views/diplomes/new.html.erb
<h1>New diplome</h1>

<%= render 'form' %>

<%= link_to 'Back', diplomes_path %>

app/views/diplomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @diplome.name %>
</p>

<p>
  <b>Student:</b>
  <%= @diplome.student_id %>
</p>


<%= link_to 'Edit', edit_diplome_path(@diplome) %> |
<%= link_to 'Back', diplomes_path %>

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :poste %><br />
    <%= f.text_field :poste %>
  </div>
  <div class="field">
    <%= f.label :debut %><br />
    <%= f.text_field :debut %>
  </div>
  <div class="field">
    <%= f.label :fin %><br />
    <%= f.text_field :fin %>
  </div>
  <div class="field">
    <%= f.label :societe %><br />
    <%= f.text_field :societe %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br />
    <%= f.number_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<h1>Listing experiences</h1>

<table>
  <tr>
    <th>Poste</th>
    <th>Debut</th>
    <th>Fin</th>
    <th>Societe</th>
    <th>Student</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @experiences.each do |experience| %>
  <tr>
    <td><%= experience.poste %></td>
    <td><%= experience.debut %></td>
    <td><%= experience.fin %></td>
    <td><%= experience.societe %></td>
    <td><%= experience.student_id %></td>
    <td><%= link_to 'Show', experience %></td>
    <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
    <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Experience', new_experience_path %>

app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Poste:</b>
  <%= @experience.poste %>
</p>

<p>
  <b>Debut:</b>
  <%= @experience.debut %>
</p>

<p>
  <b>Fin:</b>
  <%= @experience.fin %>
</p>

<p>
  <b>Societe:</b>
  <%= @experience.societe %>
</p>

<p>
  <b>Student:</b>
  <%= @experience.student_id %>
</p>


<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DbAncien</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :prenom %><br />
    <%= f.text_field :prenom %>
  </div>
  <div class="field">
    <%= f.label :promo %><br />
    <%= f.text_field :promo %>
  </div>
  <div class="field">
    <%= f.label :photo %><br />
    <%= f.text_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<%= form_tag students_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>



<h1>Listing students</h1>

<table>
  <tr>
    <th>Nom</th>
    <th>Prenom</th>
    <th>Promo</th>
    <th>Photo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<%= paginate @students unless params[:search] %>
<% @students.each do |student| %>
  <tr>
    <td><%= student.nom %></td>
    <td><%= student.prenom %></td>
    <td><%= student.promo %></td>
    <td><%= image_tag(student.photo)%></td>
    <td><%= link_to 'Show', student %></td>
  </tr>
<% end %>
</table>

<br />

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nom:</b>
  <%= @student.nom %>
</p>

<p>
  <b>Prenom:</b>
  <%= @student.prenom %>
</p>

<p>
  <b>Promo:</b>
  <%= @student.promo %>
</p>

<p>
  <b>Photo:</b></br>
  <%= image_tag(@student.photo) %>
</p>
<p>
 <b>Diplomes :</b></br>
<% @student.diplomes.each do |d| %>
	<%= d.name %> </br>
<% end %>
</p>

<p>
 <b>Experiences :</b></br>
<% @student.experiences.each do |e| %>
	Boite : <%= e.societe %> Poste : <%= e.poste %> Date : <%= e.debut %> - <%= e.fin %>  </br>
<% end %>
</p>

<%= link_to 'Back', students_path %>